# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Blog
email: david.l.castilla@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm David Lorente, I'm a web developer, check my blog for periodic rants on interactive data visualizations, javascript, react.js, 
  d3.js, svg, charts, angular...

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://github.com/davidlrnt" # the base hostname & protocol for your site
twitter_username: davidlrnt
github_username:  davidlrnt

# Build settings
markdown: kramdown
